/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TvRouteImport } from './routes/tv'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiCriarTabelasRouteImport } from './routes/api-criar-tabelas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiSsoRouteImport } from './routes/api/sso'
import { Route as AdminVendasRouteImport } from './routes/admin/vendas'
import { Route as AdminTreinamentosRouteImport } from './routes/admin/treinamentos'
import { Route as AdminQuickLinksRouteImport } from './routes/admin/quick-links'
import { Route as AdminProfilesRouteImport } from './routes/admin/profiles'
import { Route as AdminMetasRouteImport } from './routes/admin/metas'
import { Route as AdminInvitesRouteImport } from './routes/admin/invites'
import { Route as AdminIntegracoesRouteImport } from './routes/admin/integracoes'
import { Route as AdminFiliaisRouteImport } from './routes/admin/filiais'
import { Route as AdminCredenciaisRouteImport } from './routes/admin/credenciais'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminCampanhasRouteImport } from './routes/admin/campanhas'
import { Route as AdminAuditoriaRouteImport } from './routes/admin/auditoria'
import { Route as AdminAiLogsRouteImport } from './routes/admin/ai-logs'
import { Route as AdminAiConfigRouteImport } from './routes/admin/ai-config'
import { Route as ApiPublicPowerbiVendasRouteImport } from './routes/api/public/powerbi/vendas'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCriarTabelasRoute = ApiCriarTabelasRouteImport.update({
  id: '/api-criar-tabelas',
  path: '/api-criar-tabelas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSsoRoute = ApiSsoRouteImport.update({
  id: '/api/sso',
  path: '/api/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendasRoute = AdminVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTreinamentosRoute = AdminTreinamentosRouteImport.update({
  id: '/treinamentos',
  path: '/treinamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuickLinksRoute = AdminQuickLinksRouteImport.update({
  id: '/quick-links',
  path: '/quick-links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilesRoute = AdminProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetasRoute = AdminMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFiliaisRoute = AdminFiliaisRouteImport.update({
  id: '/filiais',
  path: '/filiais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCredenciaisRoute = AdminCredenciaisRouteImport.update({
  id: '/credenciais',
  path: '/credenciais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampanhasRoute = AdminCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiLogsRoute = AdminAiLogsRouteImport.update({
  id: '/ai-logs',
  path: '/ai-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiConfigRoute = AdminAiConfigRouteImport.update({
  id: '/ai-config',
  path: '/ai-config',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPowerbiVendasRoute = ApiPublicPowerbiVendasRouteImport.update({
  id: '/api/public/powerbi/vendas',
  path: '/api/public/powerbi/vendas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-criar-tabelas': typeof ApiCriarTabelasRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/tv': typeof TvRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ai-config': typeof AdminAiConfigRoute
  '/admin/ai-logs': typeof AdminAiLogsRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/credenciais': typeof AdminCredenciaisRoute
  '/admin/filiais': typeof AdminFiliaisRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/metas': typeof AdminMetasRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/quick-links': typeof AdminQuickLinksRoute
  '/admin/treinamentos': typeof AdminTreinamentosRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/api/sso': typeof ApiSsoRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/powerbi/vendas': typeof ApiPublicPowerbiVendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-criar-tabelas': typeof ApiCriarTabelasRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/tv': typeof TvRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ai-config': typeof AdminAiConfigRoute
  '/admin/ai-logs': typeof AdminAiLogsRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/credenciais': typeof AdminCredenciaisRoute
  '/admin/filiais': typeof AdminFiliaisRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/metas': typeof AdminMetasRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/quick-links': typeof AdminQuickLinksRoute
  '/admin/treinamentos': typeof AdminTreinamentosRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/api/sso': typeof ApiSsoRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/powerbi/vendas': typeof ApiPublicPowerbiVendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-criar-tabelas': typeof ApiCriarTabelasRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/tv': typeof TvRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ai-config': typeof AdminAiConfigRoute
  '/admin/ai-logs': typeof AdminAiLogsRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/credenciais': typeof AdminCredenciaisRoute
  '/admin/filiais': typeof AdminFiliaisRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/metas': typeof AdminMetasRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/quick-links': typeof AdminQuickLinksRoute
  '/admin/treinamentos': typeof AdminTreinamentosRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/api/sso': typeof ApiSsoRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/powerbi/vendas': typeof ApiPublicPowerbiVendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-criar-tabelas'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/tv'
    | '/welcome'
    | '/admin/ai-config'
    | '/admin/ai-logs'
    | '/admin/auditoria'
    | '/admin/campanhas'
    | '/admin/companies'
    | '/admin/credenciais'
    | '/admin/filiais'
    | '/admin/integracoes'
    | '/admin/invites'
    | '/admin/metas'
    | '/admin/profiles'
    | '/admin/quick-links'
    | '/admin/treinamentos'
    | '/admin/vendas'
    | '/api/sso'
    | '/admin/'
    | '/api/public/powerbi/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-criar-tabelas'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/tv'
    | '/welcome'
    | '/admin/ai-config'
    | '/admin/ai-logs'
    | '/admin/auditoria'
    | '/admin/campanhas'
    | '/admin/companies'
    | '/admin/credenciais'
    | '/admin/filiais'
    | '/admin/integracoes'
    | '/admin/invites'
    | '/admin/metas'
    | '/admin/profiles'
    | '/admin/quick-links'
    | '/admin/treinamentos'
    | '/admin/vendas'
    | '/api/sso'
    | '/admin'
    | '/api/public/powerbi/vendas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-criar-tabelas'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/tv'
    | '/welcome'
    | '/admin/ai-config'
    | '/admin/ai-logs'
    | '/admin/auditoria'
    | '/admin/campanhas'
    | '/admin/companies'
    | '/admin/credenciais'
    | '/admin/filiais'
    | '/admin/integracoes'
    | '/admin/invites'
    | '/admin/metas'
    | '/admin/profiles'
    | '/admin/quick-links'
    | '/admin/treinamentos'
    | '/admin/vendas'
    | '/api/sso'
    | '/admin/'
    | '/api/public/powerbi/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiCriarTabelasRoute: typeof ApiCriarTabelasRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  TvRoute: typeof TvRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiSsoRoute: typeof ApiSsoRoute
  ApiPublicPowerbiVendasRoute: typeof ApiPublicPowerbiVendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-criar-tabelas': {
      id: '/api-criar-tabelas'
      path: '/api-criar-tabelas'
      fullPath: '/api-criar-tabelas'
      preLoaderRoute: typeof ApiCriarTabelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/sso': {
      id: '/api/sso'
      path: '/api/sso'
      fullPath: '/api/sso'
      preLoaderRoute: typeof ApiSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendas': {
      id: '/admin/vendas'
      path: '/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AdminVendasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/treinamentos': {
      id: '/admin/treinamentos'
      path: '/treinamentos'
      fullPath: '/admin/treinamentos'
      preLoaderRoute: typeof AdminTreinamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quick-links': {
      id: '/admin/quick-links'
      path: '/quick-links'
      fullPath: '/admin/quick-links'
      preLoaderRoute: typeof AdminQuickLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profiles': {
      id: '/admin/profiles'
      path: '/profiles'
      fullPath: '/admin/profiles'
      preLoaderRoute: typeof AdminProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metas': {
      id: '/admin/metas'
      path: '/metas'
      fullPath: '/admin/metas'
      preLoaderRoute: typeof AdminMetasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/filiais': {
      id: '/admin/filiais'
      path: '/filiais'
      fullPath: '/admin/filiais'
      preLoaderRoute: typeof AdminFiliaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/credenciais': {
      id: '/admin/credenciais'
      path: '/credenciais'
      fullPath: '/admin/credenciais'
      preLoaderRoute: typeof AdminCredenciaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campanhas': {
      id: '/admin/campanhas'
      path: '/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AdminCampanhasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-logs': {
      id: '/admin/ai-logs'
      path: '/ai-logs'
      fullPath: '/admin/ai-logs'
      preLoaderRoute: typeof AdminAiLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-config': {
      id: '/admin/ai-config'
      path: '/ai-config'
      fullPath: '/admin/ai-config'
      preLoaderRoute: typeof AdminAiConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/powerbi/vendas': {
      id: '/api/public/powerbi/vendas'
      path: '/api/public/powerbi/vendas'
      fullPath: '/api/public/powerbi/vendas'
      preLoaderRoute: typeof ApiPublicPowerbiVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiConfigRoute: typeof AdminAiConfigRoute
  AdminAiLogsRoute: typeof AdminAiLogsRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminCampanhasRoute: typeof AdminCampanhasRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminCredenciaisRoute: typeof AdminCredenciaisRoute
  AdminFiliaisRoute: typeof AdminFiliaisRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminMetasRoute: typeof AdminMetasRoute
  AdminProfilesRoute: typeof AdminProfilesRoute
  AdminQuickLinksRoute: typeof AdminQuickLinksRoute
  AdminTreinamentosRoute: typeof AdminTreinamentosRoute
  AdminVendasRoute: typeof AdminVendasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiConfigRoute: AdminAiConfigRoute,
  AdminAiLogsRoute: AdminAiLogsRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminCampanhasRoute: AdminCampanhasRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminCredenciaisRoute: AdminCredenciaisRoute,
  AdminFiliaisRoute: AdminFiliaisRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AdminMetasRoute: AdminMetasRoute,
  AdminProfilesRoute: AdminProfilesRoute,
  AdminQuickLinksRoute: AdminQuickLinksRoute,
  AdminTreinamentosRoute: AdminTreinamentosRoute,
  AdminVendasRoute: AdminVendasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiCriarTabelasRoute: ApiCriarTabelasRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  TvRoute: TvRoute,
  WelcomeRoute: WelcomeRoute,
  ApiSsoRoute: ApiSsoRoute,
  ApiPublicPowerbiVendasRoute: ApiPublicPowerbiVendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
